
DmlDemo.dmlDemoInsert_standObj1();
DmlDemo.dmlDemoInsert_cstmobj();
DmlDemo.dmlUpdateDemo_standObj1();
DmlDemo.dmlUpdateDemo_standobj2();
DmlDemo.dmlInsertDemo_standOgb3();
DmlDemo.dmlDemoInsert_cstmpbj2();
DmlDemo.dmlDemoMultipleInsert_right1();
DmlDemo.dmlDemoMultipleUpdate_right1();
DmlDemo.dmlDemoMultipleUpdate_right2();
DmlDemo.dmlDemoMultipleInsert_right2();

delete [select id from account where createddate = today limit 70];
